# Generated by Django 4.1 on 2022-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('datecreated', models.IntegerField()),
                ('createdby', models.CharField(max_length=1)),
            ],
        ),
    ]
