# Generated by Django 4.1 on 2022-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='createdby',
            field=models.CharField(max_length=255),
        ),
    ]
