# Generated by Django 4.1 on 2022-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugfinder', '0002_alter_chapters_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255)),
                ('published', models.IntegerField(max_length=4)),
                ('author', models.CharField(max_length=255)),
                ('yearwritten', models.IntegerField(max_length=4)),
            ],
        ),
    ]
